#!/usr/bin/env bash
# Stage 3 of the dev harness: response.json -> findings.json + comment.md.
# Mirrors review.sh sections 5-6 and 8 (extract, validate, render, gate).
# Pure local jq — iterate on the renderer against cached responses for free.
# Never posts anywhere.
#
# Required env: FIXTURE
# Optional env: FAIL_ON_SEVERITY (default none; set to exercise the gate),
#               MODEL (label shown in the comment; default claude-opus-4-8)

. "$(dirname "${BASH_SOURCE[0]}")/common.sh"
require_fixture
require_file "$fixture_dir/response.json" "call.sh"

FAIL_ON_SEVERITY="${FAIL_ON_SEVERITY:-none}"
MODEL="${MODEL:-claude-opus-4-8}"
MARKER="<!-- ff-sec-action:ai-code-review -->"

stop_reason=$(jq -r '.stop_reason // "unknown"' "$fixture_dir/response.json")
if [ "$stop_reason" = "refusal" ]; then
  echo "Model declined this diff (stop_reason=refusal); nothing to render."
  exit 0
fi

jq -r '[.content[] | select(.type == "text")][0].text' "$fixture_dir/response.json" \
  > "$fixture_dir/findings.raw"
jq -e '.summary and (.findings | type == "array")' "$fixture_dir/findings.raw" > /dev/null \
  || { echo "error: model output did not match the findings schema." >&2; exit 1; }
jq '.' "$fixture_dir/findings.raw" > "$fixture_dir/findings.json"
rm -f "$fixture_dir/findings.raw"

findings_count=$(jq '.findings | length' "$fixture_dir/findings.json")
highest_severity=$(jq -r '
  def rank: {"critical":5,"high":4,"medium":3,"low":2,"info":1}[.] // 0;
  [.findings[].severity] | if length == 0 then "none"
  else max_by(rank) end' "$fixture_dir/findings.json")

# Keep in sync with the comment renderer in review.sh section 6.
jq -r \
  --arg marker "$MARKER" \
  --arg model "$MODEL" \
  --arg truncated "false" \
  '
  def rank: {"critical":5,"high":4,"medium":3,"low":2,"info":1}[.] // 0;
  def badge: {"critical":"🟥 CRITICAL","high":"🟧 HIGH","medium":"🟨 MEDIUM","low":"🟦 LOW","info":"⬜ INFO"}[.];
  $marker + "\n## 🤖 AI Code Review\n\n"
  + "**Overall risk:** " + (.risk_level | ascii_upcase)
  + " · **Findings:** " + (.findings | length | tostring)
  + " · Model: `" + $model + "`"
  + (if $truncated == "true" then " · ⚠️ diff truncated" else "" end)
  + "\n\n" + .summary + "\n"
  + (if (.findings | length) == 0
     then "\n✅ No issues found.\n"
     else "\n---\n"
       + ([ .findings | sort_by(-(.severity | rank))[] |
           "\n### " + (.severity | badge) + " — " + .title + "\n"
           + "`" + .file + "` (" + .location + ") · " + .category
           + " · confidence: " + .confidence + "\n\n"
           + .description + "\n\n"
           + "**Recommendation:** " + .recommendation + "\n"
         ] | join(""))
     end)
  + (if (.positive_observations | length) > 0
     then "\n---\n**Done well:** " + (.positive_observations | join(" · ")) + "\n"
     else "" end)
  + "\n<sub>Generated by ff-sec-action/ai-code-review. Findings are advisory — verify before acting.</sub>"
  ' "$fixture_dir/findings.json" > "$fixture_dir/comment.md"

echo "Rendered '$FIXTURE': ${findings_count} finding(s), highest severity: ${highest_severity}."
echo "  $fixture_dir/findings.json"
echo "  $fixture_dir/comment.md"

if [ "$FAIL_ON_SEVERITY" != "none" ]; then
  hit=$(jq -r --arg threshold "$FAIL_ON_SEVERITY" '
    def rank: {"critical":5,"high":4,"medium":3,"low":2,"info":1}[.] // 0;
    [.findings[] | select((.severity | rank) >= ($threshold | rank))] | length
  ' "$fixture_dir/findings.json")
  if [ "$hit" -gt 0 ]; then
    echo "gate: ${hit} finding(s) at or above '${FAIL_ON_SEVERITY}' — would fail the build."
    exit 1
  fi
  echo "gate: no findings at or above '${FAIL_ON_SEVERITY}' — would pass."
fi
